name = "pinterest-of-bot"
main = "dist/index.js"
compatibility_date = "2024-01-01"
workers_dev = true

# KV Namespace para armazenar preferências de idioma dos usuários
[[kv_namespaces]]
binding = "USER_PREFERENCES"
id = "9bde2d07fc6b435f95f7f5355af23950"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }
